### PR TITLE
added purge command

### PR DESCRIPTION
**Pull request by ukcai696969**
added purge command

### CODE REVIEW

**Comment by TheGamer3514** [comment]
Cool!

**Comment by KingTino104** [comment]
o thanks lemme just steal this code

**Comment by ukcai696969** [comment]
No

**Comment by TheGamer3514** [comment]
Interesting.

**Comment by Ukcai6** [comment]
> Interesting.

Shsuh I tried to reply with email but it did that 💀😂

**Comment by TheGamer3514** [comment]
Lolll

**Comment by Ukcai6** [comment]
Not funny

**Comment by TheGamer3514** [comment]
@Huguitis honestly hire this man as a dev. So good. Totally did not have to ask me how to pull request

**Comment by Ukcai6** [comment]
Bruh github has 69 diffrent functions how am I supposed to know

**Comment by TheGamer3514** [comment]
Epic ping command

**Comment by TheGamer3514** [comment]
Cool use of an api

**Comment by ukcai696969** [comment]
yesss

**Comment by ukcai696969** [comment]
im to good

**Comment by TheGamer3514** [comment]
Can you add more commands? Maybe some fun ones like 8ball ?

**Comment by TheGamer3514** [comment]
@ukcai696969

**Comment by Huguitis** [comment]
Code is outdated.

**Pull request closed without merging**
