### PR TITLE
Added More Commands (ping, serverinfo, reboot)

### PR DESCRIPTION
**Pull request by TheGamer3514**
Added some commands to the robot

### CODE REVIEW

**Comment by TheGamer3514** [comment]
Lovely
@doctormagico thanks for "allowing" me to use ur bot for testing ❤️

**Review by TheGamer3514 — COMMENTED** [review]
EPIC

**Comment by TheGamer3514** [comment]
@Huguitis

**Comment by doctormagico** [comment]
The best Pull Requester in the world :D

**Pull request merged**
