### PR TITLE
upgraded ping

### PR DESCRIPTION
**Pull request by ukcai696969**

### CODE REVIEW

**Comment by TheGamer3514** [comment]
Interesting

**Comment by TheGamer3514** [comment]
This is like so cool

**Comment by TheGamer3514** [comment]
How are you today @ukcai696969 ?

**Comment by Ukcai6** [comment]
Dm me on discord not here

**Comment by TheGamer3514** [comment]
Rude

**Comment by ukcai696969** [comment]
soory gamer love u

**Comment by TheGamer3514** [comment]
make 5000 more commands

**Comment by TheGamer3514** [comment]
add things like 8 ball

**Comment by ukcai696969** [comment]
no LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

**Comment by TheGamer3514** [comment]
LLLLLLLLLLL

**Comment by TheGamer3514** [comment]
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

**Comment by TheGamer3514** [comment]
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

**Comment by ukcai696969** [comment]
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

**Comment by TheGamer3514** [comment]
E

**Comment by TheGamer3514** [comment]
IMA ADD MORE COMMANDS
YEEEHAWWWW

**Comment by doctormagico** [comment]
Yessssss
We need more commands

**Comment by doctormagico** [comment]
Add ticket system or maybe..... music

**Comment by Ukcai6** [comment]
Might add music later

**Comment by TheGamer3514** [comment]
> Might add music later

have you?

**Comment by TheGamer3514** [comment]
cause would be cool

**Comment by TheGamer3514** [comment]
copy
paste
@Huguitis i think u should close this and let me do it in a pull 😆

**Comment by TheGamer3514** [comment]
made better #14

**Pull request closed without merging**
